/*!
 * @file main.c
 * @brief PULSE Click Example.
 *
 * # Description
 * This example demonstrates the use of the PULSE Click board by monitoring
 * the pulse signal generated by the NE555 timer on the selected pin (OUT or INT)
 * and logging every change of its logic state on the USB UART.
 *
 * The demo application is composed of two sections :
 *
 * ## Application Init
 * Initializes the driver and logger, and reads the initial logic state of the selected pin.
 *
 * ## Application Task
 * Polls the selected pin and logs its new logic state each time the pulse signal
 * changes its level.
 *
 * @note
 * The selected pin must match the J1 jumper position on the Click board.
 *
 * @author Milan Ivancic
 *
 */

#include "board.h"
#include "log.h"
#include "pulse.h"

#ifndef MIKROBUS_POSITION_PULSE
    #define MIKROBUS_POSITION_PULSE MIKROBUS_1
#endif

// Comment out the line below in order to switch the demo to the INT pin
#define DEMO_PIN_OUT

#ifdef DEMO_PIN_OUT
    #define DEMO_PULSE_PIN              PULSE_PIN_OUT
    #define DEMO_PIN_NAME               "OUT"
#else
    #define DEMO_PULSE_PIN              PULSE_PIN_INT
    #define DEMO_PIN_NAME               "INT"
#endif

static pulse_t pulse;   /**< PULSE Click driver object. */
static log_t logger;    /**< Logger object. */
static uint8_t pin_state = 0; /**< Last known logic state of the selected pin */

void application_init ( void ) 
{
    log_cfg_t log_cfg;  /**< Logger config object. */
    pulse_cfg_t pulse_cfg;  /**< Click config object. */

    /** 
     * Logger initialization.
     * Default baud rate: 115200
     * Default log level: LOG_LEVEL_DEBUG
     * @note If USB_UART_RX and USB_UART_TX 
     * are defined as HAL_PIN_NC, you will 
     * need to define them manually for log to work. 
     * See @b LOG_MAP_USB_UART macro definition for detailed explanation.
     */
    LOG_MAP_USB_UART( log_cfg );
    log_init( &logger, &log_cfg );
    log_info( &logger, " Application Init " );

    // Click initialization.
    pulse_cfg_setup( &pulse_cfg );
    PULSE_MAP_MIKROBUS( pulse_cfg, MIKROBUS_POSITION_PULSE );
    if ( DIGITAL_OUT_UNSUPPORTED_PIN == pulse_init( &pulse, &pulse_cfg ) ) 
    {
        log_error( &logger, " Communication init." );
        for ( ; ; );
    }

    /* Store the initial state of the selected pin */
    pulse_read_pin( &pulse, DEMO_PULSE_PIN, &pin_state );
    
    log_info( &logger, " Application Task " );
}

void application_task ( void ) 
{
    uint8_t new_state = 0;

    if ( ( PULSE_OK == pulse_read_pin( &pulse, DEMO_PULSE_PIN, &new_state ) ) && 
         ( new_state != pin_state ) )
    {
        pin_state = new_state;
        if ( pin_state )
        {
            log_printf( &logger, " %s pin: HIGH\r\n", DEMO_PIN_NAME );
        }
        else
        {
            log_printf( &logger, " %s pin: LOW\r\n\n", DEMO_PIN_NAME );
        }
    }
}

int main ( void ) 
{
    /* Do not remove this line or clock might not be set correctly. */
    #ifdef PREINIT_SUPPORTED
    preinit();
    #endif
    
    application_init( );
    
    for ( ; ; ) 
    {
        application_task( );
    }

    return 0;
}

// ------------------------------------------------------------------------ END
