/*!
 * @file main.c
 * @brief RNG 2 Click example
 *
 * # Description
 * This example demonstrates the use of the RNG 2 Click board by periodically reading 
 * and logging random numbers generated by the device.
 *
 * The demo application is composed of two sections :
 *
 * ## Application Init
 * Initializes the logger and the Click board driver, then applies the default configuration.
 *
 * ## Application Task
 * Reads and displays a 32-byte random number from the device every second.
 *
 * @author Stefan Filipovic
 *
 */

#include "board.h"
#include "log.h"
#include "rng2.h"

static rng2_t rng2;
static log_t logger;

void application_init ( void ) 
{
    log_cfg_t log_cfg;  /**< Logger config object. */
    rng2_cfg_t rng2_cfg;  /**< Click config object. */

    /** 
     * Logger initialization.
     * Default baud rate: 115200
     * Default log level: LOG_LEVEL_DEBUG
     * @note If USB_UART_RX and USB_UART_TX 
     * are defined as HAL_PIN_NC, you will 
     * need to define them manually for log to work. 
     * See @b LOG_MAP_USB_UART macro definition for detailed explanation.
     */
    LOG_MAP_USB_UART( log_cfg );
    log_init( &logger, &log_cfg );
    log_info( &logger, " Application Init " );

    // Click initialization.
    rng2_cfg_setup( &rng2_cfg );
    RNG2_MAP_MIKROBUS( rng2_cfg, MIKROBUS_1 );
    if ( RNG2_OK != rng2_init( &rng2, &rng2_cfg ) ) 
    {
        log_error( &logger, " Communication init." );
        for ( ; ; );
    }
    
    if ( RNG2_ERROR == rng2_default_cfg ( &rng2 ) )
    {
        log_error( &logger, " Default configuration." );
        for ( ; ; );
    }
    
    log_info( &logger, " Application Task " );
}

void application_task ( void ) 
{
    if ( RNG2_OK == rng2_read_random_num ( &rng2 ) )
    {
        log_printf ( &logger, " Random number: " );
        for ( uint8_t cnt = 0; cnt < rng2.rsp_pkt.data_len; cnt++ )
        {
            log_printf ( &logger, "%.2X", ( uint16_t ) rng2.rsp_pkt.data_buf[ cnt ] );
        }
        log_printf ( &logger, "\r\n\n" );
    }
    Delay_ms ( 1000 );
}

int main ( void ) 
{
    /* Do not remove this line or clock might not be set correctly. */
    #ifdef PREINIT_SUPPORTED
    preinit();
    #endif
    
    application_init( );
    
    for ( ; ; ) 
    {
        application_task( );
    }

    return 0;
}

// ------------------------------------------------------------------------ END
